import '@/tokens/index.scss';
import '@/styles/index.scss';

import type { Metadata } from 'next';

import cn from 'classnames';

import { Column, Flex, Header } from '@/components';
import { font } from '@/resources';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Flex
      suppressHydrationWarning
      as="html"
      lang="en"
      className={cn(
        font.primary.variable,
        font.secondary.variable,
        font.tertiary.variable
      )}
    >
      <Column
        style={{ minHeight: '100vh' }}
        as="body"
        fillWidth
        margin="0"
        padding="0"
      >
        <Header />
        <Flex
          zIndex={0}
          fillWidth
          flex={1}
          paddingY="l"
          paddingX="l"
          horizontal="center"
        >
          <Flex horizontal="center" fillWidth minHeight="0">
            {children}
          </Flex>
        </Flex>
      </Column>
    </Flex>
  );
}
